import cards from "./blogOgCards.json" with { type: "json" };

/**
 * Returns the current versioned OG preview card URL for a blog slug, or
 * `null` if no generated card exists (caller should fall back to the
 * post's hero image). Generated by scripts/generate-og-cards.mjs during
 * prebuild; the file path itself contains a content hash so any change
 * to the hero image or headline invalidates the URL and prevents stale
 * Twitter/Facebook/LinkedIn previews from being served after republish.
 */
type CardEntry = { url: string; hash: string; width: number; height: number };
const map = cards as Record<string, CardEntry>;

export function getBlogOgCard(slug: string): CardEntry | null {
  return map[slug] ?? null;
}

export function getBlogOgCardUrl(slug: string, absolute = true): string | null {
  const c = map[slug];
  if (!c) return null;
  return absolute ? `https://weddings.io${c.url}` : c.url;
}
