import manifest from "./blogImageManifest.json" with { type: "json" };

/**
 * Append a short content-hash query string to a blog image URL so
 * CDN + browser caches always fetch the freshest variant after
 * republishing. If the file isn't in the manifest (external URL,
 * asset-CDN pointer, or new file before prebuild ran), returns the
 * URL unchanged.
 *
 * Manifest is regenerated by `scripts/build-image-manifest.mjs`,
 * which runs as part of prebuild.
 */
const map = manifest as Record<string, string>;

export function withImageVersion<T extends string | undefined | null>(url: T): T {
  if (!url || typeof url !== "string") return url;
  if (url.includes("?")) return url; // caller already versioned
  if (/^https?:\/\//i.test(url) && !url.startsWith("https://weddings.io/")) return url;
  const path = url.replace(/^https:\/\/weddings\.io/, "");
  const hash = map[path];
  return (hash ? `${url}?v=${hash}` : url) as T;
}
