// Build metadata — regenerated by scripts/write-build-info.mjs on every build/publish.
export const BUILD_COMMIT_SHORT = "95ebf1d";
export const BUILD_COMMIT_FULL = "95ebf1df7288c9bb6985dab56bb10852eb126281";
export const BUILD_TIME_ISO = "2026-07-20T18:54:36Z";
export const BUILD_TIME_LABEL = "Jul 20 · 2026, 18:54 UTC";
export const BUILD_CACHE_BUSTER = "95ebf1d-2026-07-20T18:54:36Z";
export const LATEST_PRICING_CODE_VERSION = "95ebf1df7288c9bb6985dab56bb10852eb126281";
