// Build metadata — regenerated by scripts/write-build-info.mjs on every build/publish.
export const BUILD_COMMIT_SHORT = "15b46ef";
export const BUILD_COMMIT_FULL = "15b46efcfd7ce713a65628c2210d8088091ce6cb";
export const BUILD_TIME_ISO = "2026-07-23T04:45:25Z";
export const BUILD_TIME_LABEL = "Jul 23 · 2026, 04:45 UTC";
export const BUILD_CACHE_BUSTER = "15b46ef-2026-07-23T04:45:25Z";
export const LATEST_PRICING_CODE_VERSION = "15b46efcfd7ce713a65628c2210d8088091ce6cb";
