// Build metadata — regenerated by scripts/write-build-info.mjs on every build/publish.
export const BUILD_COMMIT_SHORT = "a278b78";
export const BUILD_COMMIT_FULL = "a278b7854586d2a0a66a60c5a482ed7c0fde8966";
export const BUILD_TIME_ISO = "2026-07-17T02:21:33Z";
export const BUILD_TIME_LABEL = "Jul 17 · 2026, 02:21 UTC";
export const BUILD_CACHE_BUSTER = "a278b78-2026-07-17T02:21:33Z";
export const LATEST_PRICING_CODE_VERSION = "a278b7854586d2a0a66a60c5a482ed7c0fde8966";
