import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";

export const Route = createFileRoute("/admin/policy-audit")({
  head: () => ({
    meta: [
      { title: "Policy Change Audit Log | Admin" },
      { name: "robots", content: "noindex, nofollow" },
    ],
  }),
  component: PolicyAuditPage,
});

type Change = { kind: string; policy?: string; target: string };
type Entry = {
  migration: string;
  commit: string;
  committed_at: string | null;
  subject: string;
  change_count: number;
  changes: Change[];
  history: { commit: string; committed_at: string | null; subject: string }[];
};
type Audit = { generated_at: string; total: number; entries: Entry[] };

function PolicyAuditPage() {
  const [audit, setAudit] = useState<Audit | null>(null);
  const [err, setErr] = useState<string | null>(null);

  useEffect(() => {
    fetch("/policy-audit.json", { cache: "no-store" })
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(String(r.status)))))
      .then(setAudit)
      .catch((e) => setErr(e.message ?? String(e)));
  }, []);

  return (
    <main className="mx-auto max-w-5xl px-4 py-10">
      <h1 className="text-3xl font-bold tracking-tight">RLS &amp; Storage Policy Audit Log</h1>
      <p className="mt-2 text-sm text-muted-foreground">
        Every migration under <code>supabase/migrations/</code> that adds, drops, alters, or grants access to
        an RLS/storage policy — with its commit SHA and commit timestamp. Regenerated by{" "}
        <code>scripts/build-policy-audit.mjs</code> (runs in <code>prebuild</code>).
      </p>

      {err && (
        <p className="mt-6 rounded-md border border-destructive/40 bg-destructive/10 p-4 text-sm text-destructive">
          Failed to load audit log: {err}. Run <code>node scripts/build-policy-audit.mjs</code>.
        </p>
      )}

      {audit && (
        <>
          <p className="mt-6 text-xs text-muted-foreground">
            Generated {new Date(audit.generated_at).toLocaleString()} · {audit.total} policy-changing
            migration(s)
          </p>
          <ul className="mt-6 space-y-4">
            {audit.entries.map((e) => (
              <li key={e.migration} className="rounded-lg border border-border bg-card p-4">
                <div className="flex flex-wrap items-baseline justify-between gap-2">
                  <h2 className="font-mono text-sm font-semibold">{e.migration}</h2>
                  <span className="text-xs text-muted-foreground">
                    {e.committed_at ? new Date(e.committed_at).toLocaleString() : "uncommitted"} ·{" "}
                    <code>{e.commit.slice(0, 8)}</code>
                  </span>
                </div>
                {e.subject && <p className="mt-1 text-sm text-muted-foreground">{e.subject}</p>}
                <ul className="mt-3 space-y-1 text-sm">
                  {e.changes.map((c, i) => (
                    <li key={i} className="flex flex-wrap gap-2">
                      <span className="rounded bg-muted px-2 py-0.5 font-mono text-xs">{c.kind}</span>
                      {c.policy && (
                        <span className="font-mono text-xs">
                          &ldquo;{c.policy}&rdquo;
                        </span>
                      )}
                      <span className="font-mono text-xs text-muted-foreground">on {c.target}</span>
                    </li>
                  ))}
                </ul>
              </li>
            ))}
          </ul>
        </>
      )}
    </main>
  );
}
