/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualizerRouteImport } from './routes/visualizer'
import { Route as VenuesRouteImport } from './routes/venues'
import { Route as TalcRouteImport } from './routes/talc'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PlannersRouteImport } from './routes/planners'
import { Route as GuestPostRouteImport } from './routes/guest-post'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as CulturesRouteImport } from './routes/cultures'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BacklinksRouteImport } from './routes/backlinks'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiRouteImport } from './routes/ai'
import { Route as WhoOwnsWeddingsDotioRouteImport } from './routes/Who-Owns-Weddings[.]io'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorsIndexRouteImport } from './routes/vendors.index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as WallEventCodeRouteImport } from './routes/wall.$eventCode'
import { Route as VipTrustedCodeRouteImport } from './routes/vip.$trustedCode'
import { Route as VendorsSlugRouteImport } from './routes/vendors.$slug'
import { Route as ToolsCultureRouteImport } from './routes/tools.$culture'
import { Route as PortalPhotoWallRouteImport } from './routes/portal.photo-wall'
import { Route as GEventCodeRouteImport } from './routes/g.$eventCode'
import { Route as DashboardPositionOneRouteImport } from './routes/dashboard.position-one'
import { Route as CheckoutSplatRouteImport } from './routes/checkout.$'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminEyespyrRouteImport } from './routes/admin.eyespyr'
import { Route as BlogPagePageRouteImport } from './routes/blog.page.$page'

const VisualizerRoute = VisualizerRouteImport.update({
  id: '/visualizer',
  path: '/visualizer',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesRoute = VenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const TalcRoute = TalcRouteImport.update({
  id: '/talc',
  path: '/talc',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannersRoute = PlannersRouteImport.update({
  id: '/planners',
  path: '/planners',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestPostRoute = GuestPostRouteImport.update({
  id: '/guest-post',
  path: '/guest-post',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const CulturesRoute = CulturesRouteImport.update({
  id: '/cultures',
  path: '/cultures',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklinksRoute = BacklinksRouteImport.update({
  id: '/backlinks',
  path: '/backlinks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoOwnsWeddingsDotioRoute = WhoOwnsWeddingsDotioRouteImport.update({
  id: '/Who-Owns-Weddings.io',
  path: '/Who-Owns-Weddings.io',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const WallEventCodeRoute = WallEventCodeRouteImport.update({
  id: '/wall/$eventCode',
  path: '/wall/$eventCode',
  getParentRoute: () => rootRouteImport,
} as any)
const VipTrustedCodeRoute = VipTrustedCodeRouteImport.update({
  id: '/vip/$trustedCode',
  path: '/vip/$trustedCode',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsSlugRoute = VendorsSlugRouteImport.update({
  id: '/vendors/$slug',
  path: '/vendors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCultureRoute = ToolsCultureRouteImport.update({
  id: '/tools/$culture',
  path: '/tools/$culture',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPhotoWallRoute = PortalPhotoWallRouteImport.update({
  id: '/photo-wall',
  path: '/photo-wall',
  getParentRoute: () => PortalRoute,
} as any)
const GEventCodeRoute = GEventCodeRouteImport.update({
  id: '/g/$eventCode',
  path: '/g/$eventCode',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPositionOneRoute = DashboardPositionOneRouteImport.update({
  id: '/dashboard/position-one',
  path: '/dashboard/position-one',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSplatRoute = CheckoutSplatRouteImport.update({
  id: '/checkout/$',
  path: '/checkout/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminEyespyrRoute = AdminEyespyrRouteImport.update({
  id: '/admin/eyespyr',
  path: '/admin/eyespyr',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPagePageRoute = BlogPagePageRouteImport.update({
  id: '/page/$page',
  path: '/page/$page',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Who-Owns-Weddings.io': typeof WhoOwnsWeddingsDotioRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/backlinks': typeof BacklinksRoute
  '/blog': typeof BlogRouteWithChildren
  '/checklist': typeof ChecklistRoute
  '/cities': typeof CitiesRoute
  '/contribute': typeof ContributeRoute
  '/cultures': typeof CulturesRoute
  '/destinations': typeof DestinationsRoute
  '/ecosystem': typeof EcosystemRoute
  '/features': typeof FeaturesRoute
  '/guest-post': typeof GuestPostRoute
  '/planners': typeof PlannersRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/talc': typeof TalcRoute
  '/venues': typeof VenuesRoute
  '/visualizer': typeof VisualizerRoute
  '/admin/eyespyr': typeof AdminEyespyrRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/$': typeof CheckoutSplatRoute
  '/dashboard/position-one': typeof DashboardPositionOneRoute
  '/g/$eventCode': typeof GEventCodeRoute
  '/portal/photo-wall': typeof PortalPhotoWallRoute
  '/tools/$culture': typeof ToolsCultureRoute
  '/vendors/$slug': typeof VendorsSlugRoute
  '/vip/$trustedCode': typeof VipTrustedCodeRoute
  '/wall/$eventCode': typeof WallEventCodeRoute
  '/blog/': typeof BlogIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/blog/page/$page': typeof BlogPagePageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Who-Owns-Weddings.io': typeof WhoOwnsWeddingsDotioRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/backlinks': typeof BacklinksRoute
  '/checklist': typeof ChecklistRoute
  '/cities': typeof CitiesRoute
  '/contribute': typeof ContributeRoute
  '/cultures': typeof CulturesRoute
  '/destinations': typeof DestinationsRoute
  '/ecosystem': typeof EcosystemRoute
  '/features': typeof FeaturesRoute
  '/guest-post': typeof GuestPostRoute
  '/planners': typeof PlannersRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/talc': typeof TalcRoute
  '/venues': typeof VenuesRoute
  '/visualizer': typeof VisualizerRoute
  '/admin/eyespyr': typeof AdminEyespyrRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/$': typeof CheckoutSplatRoute
  '/dashboard/position-one': typeof DashboardPositionOneRoute
  '/g/$eventCode': typeof GEventCodeRoute
  '/portal/photo-wall': typeof PortalPhotoWallRoute
  '/tools/$culture': typeof ToolsCultureRoute
  '/vendors/$slug': typeof VendorsSlugRoute
  '/vip/$trustedCode': typeof VipTrustedCodeRoute
  '/wall/$eventCode': typeof WallEventCodeRoute
  '/blog': typeof BlogIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/vendors': typeof VendorsIndexRoute
  '/blog/page/$page': typeof BlogPagePageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Who-Owns-Weddings.io': typeof WhoOwnsWeddingsDotioRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/backlinks': typeof BacklinksRoute
  '/blog': typeof BlogRouteWithChildren
  '/checklist': typeof ChecklistRoute
  '/cities': typeof CitiesRoute
  '/contribute': typeof ContributeRoute
  '/cultures': typeof CulturesRoute
  '/destinations': typeof DestinationsRoute
  '/ecosystem': typeof EcosystemRoute
  '/features': typeof FeaturesRoute
  '/guest-post': typeof GuestPostRoute
  '/planners': typeof PlannersRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/talc': typeof TalcRoute
  '/venues': typeof VenuesRoute
  '/visualizer': typeof VisualizerRoute
  '/admin/eyespyr': typeof AdminEyespyrRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/$': typeof CheckoutSplatRoute
  '/dashboard/position-one': typeof DashboardPositionOneRoute
  '/g/$eventCode': typeof GEventCodeRoute
  '/portal/photo-wall': typeof PortalPhotoWallRoute
  '/tools/$culture': typeof ToolsCultureRoute
  '/vendors/$slug': typeof VendorsSlugRoute
  '/vip/$trustedCode': typeof VipTrustedCodeRoute
  '/wall/$eventCode': typeof WallEventCodeRoute
  '/blog/': typeof BlogIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/blog/page/$page': typeof BlogPagePageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Who-Owns-Weddings.io'
    | '/ai'
    | '/auth'
    | '/backlinks'
    | '/blog'
    | '/checklist'
    | '/cities'
    | '/contribute'
    | '/cultures'
    | '/destinations'
    | '/ecosystem'
    | '/features'
    | '/guest-post'
    | '/planners'
    | '/portal'
    | '/pricing'
    | '/talc'
    | '/venues'
    | '/visualizer'
    | '/admin/eyespyr'
    | '/blog/$slug'
    | '/checkout/$'
    | '/dashboard/position-one'
    | '/g/$eventCode'
    | '/portal/photo-wall'
    | '/tools/$culture'
    | '/vendors/$slug'
    | '/vip/$trustedCode'
    | '/wall/$eventCode'
    | '/blog/'
    | '/tools/'
    | '/vendors/'
    | '/blog/page/$page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Who-Owns-Weddings.io'
    | '/ai'
    | '/auth'
    | '/backlinks'
    | '/checklist'
    | '/cities'
    | '/contribute'
    | '/cultures'
    | '/destinations'
    | '/ecosystem'
    | '/features'
    | '/guest-post'
    | '/planners'
    | '/portal'
    | '/pricing'
    | '/talc'
    | '/venues'
    | '/visualizer'
    | '/admin/eyespyr'
    | '/blog/$slug'
    | '/checkout/$'
    | '/dashboard/position-one'
    | '/g/$eventCode'
    | '/portal/photo-wall'
    | '/tools/$culture'
    | '/vendors/$slug'
    | '/vip/$trustedCode'
    | '/wall/$eventCode'
    | '/blog'
    | '/tools'
    | '/vendors'
    | '/blog/page/$page'
  id:
    | '__root__'
    | '/'
    | '/Who-Owns-Weddings.io'
    | '/ai'
    | '/auth'
    | '/backlinks'
    | '/blog'
    | '/checklist'
    | '/cities'
    | '/contribute'
    | '/cultures'
    | '/destinations'
    | '/ecosystem'
    | '/features'
    | '/guest-post'
    | '/planners'
    | '/portal'
    | '/pricing'
    | '/talc'
    | '/venues'
    | '/visualizer'
    | '/admin/eyespyr'
    | '/blog/$slug'
    | '/checkout/$'
    | '/dashboard/position-one'
    | '/g/$eventCode'
    | '/portal/photo-wall'
    | '/tools/$culture'
    | '/vendors/$slug'
    | '/vip/$trustedCode'
    | '/wall/$eventCode'
    | '/blog/'
    | '/tools/'
    | '/vendors/'
    | '/blog/page/$page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WhoOwnsWeddingsDotioRoute: typeof WhoOwnsWeddingsDotioRoute
  AiRoute: typeof AiRoute
  AuthRoute: typeof AuthRoute
  BacklinksRoute: typeof BacklinksRoute
  BlogRoute: typeof BlogRouteWithChildren
  ChecklistRoute: typeof ChecklistRoute
  CitiesRoute: typeof CitiesRoute
  ContributeRoute: typeof ContributeRoute
  CulturesRoute: typeof CulturesRoute
  DestinationsRoute: typeof DestinationsRoute
  EcosystemRoute: typeof EcosystemRoute
  FeaturesRoute: typeof FeaturesRoute
  GuestPostRoute: typeof GuestPostRoute
  PlannersRoute: typeof PlannersRoute
  PortalRoute: typeof PortalRouteWithChildren
  PricingRoute: typeof PricingRoute
  TalcRoute: typeof TalcRoute
  VenuesRoute: typeof VenuesRoute
  VisualizerRoute: typeof VisualizerRoute
  AdminEyespyrRoute: typeof AdminEyespyrRoute
  CheckoutSplatRoute: typeof CheckoutSplatRoute
  DashboardPositionOneRoute: typeof DashboardPositionOneRoute
  GEventCodeRoute: typeof GEventCodeRoute
  ToolsCultureRoute: typeof ToolsCultureRoute
  VendorsSlugRoute: typeof VendorsSlugRoute
  VipTrustedCodeRoute: typeof VipTrustedCodeRoute
  WallEventCodeRoute: typeof WallEventCodeRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visualizer': {
      id: '/visualizer'
      path: '/visualizer'
      fullPath: '/visualizer'
      preLoaderRoute: typeof VisualizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues': {
      id: '/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof VenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talc': {
      id: '/talc'
      path: '/talc'
      fullPath: '/talc'
      preLoaderRoute: typeof TalcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planners': {
      id: '/planners'
      path: '/planners'
      fullPath: '/planners'
      preLoaderRoute: typeof PlannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-post': {
      id: '/guest-post'
      path: '/guest-post'
      fullPath: '/guest-post'
      preLoaderRoute: typeof GuestPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cultures': {
      id: '/cultures'
      path: '/cultures'
      fullPath: '/cultures'
      preLoaderRoute: typeof CulturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlinks': {
      id: '/backlinks'
      path: '/backlinks'
      fullPath: '/backlinks'
      preLoaderRoute: typeof BacklinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Who-Owns-Weddings.io': {
      id: '/Who-Owns-Weddings.io'
      path: '/Who-Owns-Weddings.io'
      fullPath: '/Who-Owns-Weddings.io'
      preLoaderRoute: typeof WhoOwnsWeddingsDotioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/wall/$eventCode': {
      id: '/wall/$eventCode'
      path: '/wall/$eventCode'
      fullPath: '/wall/$eventCode'
      preLoaderRoute: typeof WallEventCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip/$trustedCode': {
      id: '/vip/$trustedCode'
      path: '/vip/$trustedCode'
      fullPath: '/vip/$trustedCode'
      preLoaderRoute: typeof VipTrustedCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/$slug': {
      id: '/vendors/$slug'
      path: '/vendors/$slug'
      fullPath: '/vendors/$slug'
      preLoaderRoute: typeof VendorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$culture': {
      id: '/tools/$culture'
      path: '/tools/$culture'
      fullPath: '/tools/$culture'
      preLoaderRoute: typeof ToolsCultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/photo-wall': {
      id: '/portal/photo-wall'
      path: '/photo-wall'
      fullPath: '/portal/photo-wall'
      preLoaderRoute: typeof PortalPhotoWallRouteImport
      parentRoute: typeof PortalRoute
    }
    '/g/$eventCode': {
      id: '/g/$eventCode'
      path: '/g/$eventCode'
      fullPath: '/g/$eventCode'
      preLoaderRoute: typeof GEventCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/position-one': {
      id: '/dashboard/position-one'
      path: '/dashboard/position-one'
      fullPath: '/dashboard/position-one'
      preLoaderRoute: typeof DashboardPositionOneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$': {
      id: '/checkout/$'
      path: '/checkout/$'
      fullPath: '/checkout/$'
      preLoaderRoute: typeof CheckoutSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/eyespyr': {
      id: '/admin/eyespyr'
      path: '/admin/eyespyr'
      fullPath: '/admin/eyespyr'
      preLoaderRoute: typeof AdminEyespyrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/page/$page': {
      id: '/blog/page/$page'
      path: '/page/$page'
      fullPath: '/blog/page/$page'
      preLoaderRoute: typeof BlogPagePageRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogPagePageRoute: typeof BlogPagePageRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogPagePageRoute: BlogPagePageRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface PortalRouteChildren {
  PortalPhotoWallRoute: typeof PortalPhotoWallRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalPhotoWallRoute: PortalPhotoWallRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WhoOwnsWeddingsDotioRoute: WhoOwnsWeddingsDotioRoute,
  AiRoute: AiRoute,
  AuthRoute: AuthRoute,
  BacklinksRoute: BacklinksRoute,
  BlogRoute: BlogRouteWithChildren,
  ChecklistRoute: ChecklistRoute,
  CitiesRoute: CitiesRoute,
  ContributeRoute: ContributeRoute,
  CulturesRoute: CulturesRoute,
  DestinationsRoute: DestinationsRoute,
  EcosystemRoute: EcosystemRoute,
  FeaturesRoute: FeaturesRoute,
  GuestPostRoute: GuestPostRoute,
  PlannersRoute: PlannersRoute,
  PortalRoute: PortalRouteWithChildren,
  PricingRoute: PricingRoute,
  TalcRoute: TalcRoute,
  VenuesRoute: VenuesRoute,
  VisualizerRoute: VisualizerRoute,
  AdminEyespyrRoute: AdminEyespyrRoute,
  CheckoutSplatRoute: CheckoutSplatRoute,
  DashboardPositionOneRoute: DashboardPositionOneRoute,
  GEventCodeRoute: GEventCodeRoute,
  ToolsCultureRoute: ToolsCultureRoute,
  VendorsSlugRoute: VendorsSlugRoute,
  VipTrustedCodeRoute: VipTrustedCodeRoute,
  WallEventCodeRoute: WallEventCodeRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  VendorsIndexRoute: VendorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
